define(function() {
    return {
        "properties": [{
            "name": "left1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "chartVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "isVisibleAddRow",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headerName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "spreadsheetid",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "column1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "range",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "column2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "column3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "column4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "chartrange",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lastRowFirst",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "flxDetail",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["fetchAndSetData"],
        "events": ["onClickLogOut"]
    }
});